### ISSUE TITLE
Tamagochi.rb

### ISSUE THREAD

**Issue by RoRElessar** [Sedated1337/RubyHW#2]
Как и в предыдущем случае - форматирование не выдерживает никакой критики. Так что, как и было обещано, полбала будет точно отнято.
Касательно самого гема, который нужно было подключить. Я вижу только то, что ты подключаешь сам файл, при чем сам гем более нигде не используется. Я не могу засчитать выполнение этого задания.
Мне так же не понятно, зачем в метод `initialize` ты передаешь столько параметров, когда в твоем случае достаточно передать только `name`.

**Comment by Sedated1337** [comment]
Исправил
